### ISSUE TITLE
[1.21] `ModInfo#getModProperties` is now returning an empty map

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#10015]
**Minecraft Version:** 1.21
**Forge Version:** 51.0.8

**Description of issue:**
Updating my mods to 1.21, and `ModInfo#getModProperties` no longer returns the properties I defined in my `mods.toml`. I did some quick debugging when it calls `getConfigElement("modproperties", this.modId)` in `ModInfo` constructor and it's expecting a `StampedConfig` sub config, however it's a `SimpleCommentedConfig` and returns `null` for the modproperties. 

The definition in my `mods.toml` (has not been touched)
```toml
[modproperties."catalogue"]
    catalogueImageIcon="assets/catalogue/icon.png"
    catalogueBackground="assets/catalogue/background.png"
```
