### ISSUE TITLE
[1.14.4] ConfigValue<Object> is not supported - preventing use of tables

### ISSUE THREAD

**Issue by axieum** [MinecraftForge/MinecraftForge#6211]
Night Config allows conversion of config data to objects, essentially allowing us to implement tables.

Here is an example configuration file:
```toml
#Channel configurations
[[keys]]
	id = 242318118340805120
	whitelist = [0]

	[keys.a]
		a = "a message"
		b = "b message"

[[keys]]
	id = 262311018300915141
	whitelist = [-1, 1]

	[keys.a]
		b = "b message"
```

Which can be generated by the following:
```java
// ...
public static ForgeConfigSpec.ConfigValue<List<KeyConfig>> KEYS;

static {
        KEYS = COMMON_BUILDER.comment("Key configurations")
                                 .define("keys", new ArrayList<>());
        // ...
}

public static void loadConfig(ForgeConfigSpec spec, Path path)
{
    // ...
    configData.load();
    spec.setConfig(configData);

    // TODO: Figure out how to put this `kcfg.keys` list into the KEYS ConfigValue
    // TODO: Figure out how to do this conversion on config update
    KeysConfig kcfg= new ObjectConverter().toObject(configData, KeysConfig::new);
    List<KeyConfig> keys = kcfg.keys;
}

// ...

public static class KeysConfig
{
    public List<KeyConfig> keys;
}

public class KeyConfig
{
    public long id;
    public List<Integer> whitelist;
    public A a;

    public static class A
    {
        public String a, b;
    }
}
```

Here is Night Config's documentation on [Object serialisation](https://github.com/TheElectronWill/night-config/wiki/Object-serialization).

Essentially, we need a way to specify _in the builder_ if the definition is an object and if so, the supplier/class.

**Comment by axieum** [comment]
I will look into making a PR now, I'll let you know how I go.

**Comment by axieum** [comment]
I tried to see about adding the concept of a configuration value transformer, but had no luck. Here is what I hoped to achieve:
```java
TABLE = COMMON_BUILDER.comment("Table configurations")
                      .transform(config -> {
                          System.out.println("Transforming config entry to object instance...")
                          return new ObjectConverter().toObject(config, TablesConfig::class).tables;
                      })
                      .define("tables", new ArrayList<>());
```

**Comment by axieum** [comment]
Please see the above pull request for my own mod, I implemented a workaround until tables are supported: Axieum/MDC#1

**Comment by axieum** [comment]
It appears that this issue not only applies to arrays of tables, but also just a table/object in general.
```toml
#Command configurations
[[commands]]
    aliases = ["enroll", "wl"]
    name = "whitelist"
    command = "whitelist {}"

[[commands]]
    aliases = ["hardness"]
    name = "difficulty"
    command = "difficulty {0}"
```
